name: To Build And Deploy Java Apps

on:
  push:
    branches:
      - main

jobs:
  version_checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - run: java --version
        shell: bash
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: javac Main.java
        shell: bash
      - run: java Main
        shell: bash

